version: "3.8"

services:
  app:
    image: abj/app:latest  # Replace with the built image and tag
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    deploy:
      restart_policy:
        condition: any  # Swarm restart policy
    
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    deploy:
      restart_policy:
        condition: any
