version: "2"

services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
